import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { CallerContext } from '../src/auth/rbac.js';
import type { OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { KnowledgeSearchHit } from '../src/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching the
// convention in tests/agentCoreLanguagePreference.test.ts. DATABASE_URL is
// unreachable; the only repository export this file overrides is
// searchKnowledge, so it can simulate a knowledge_search tool call's hits
// deterministically without a real DB or embedding model — every other
// repository call the exercised knowledge_search handler makes
// (recordKnowledgeRetrieval, hasConflictAmongIds) is fire-and-forget/
// `.catch()`-guarded or skipped by this file's fixture shapes (a single hit
// never triggers the >=2-id conflict check), so it degrades harmlessly
// against the unreachable DB exactly like every other test in this style.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@localhost:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';

const FIXED_DATE = new Date('2024-01-01T00:00:00Z');

function makeHit(id: number, similarity: number): KnowledgeSearchHit {
  return {
    id,
    title: `Entry ${id}`,
    content: `Content for entry ${id}, long enough to read naturally in a reply.`,
    similarity,
    updatedAt: FIXED_DATE,
    autoGenerated: false,
    sourceUrl: null,
    sourceTitle: null,
    verifiedAt: null,
    lastRetrievedAt: null,
  };
}

// Keyed by the exact query string a simulated knowledge_search tool call
// passes — qualifying entries clear KNOWLEDGE_SEARCH_RELEVANCE_THRESHOLD
// (0.35, see storage/repository.ts), the below-floor one deliberately sits
// under it.
const HIT_FIXTURES: Record<string, KnowledgeSearchHit[]> = {
  'qualifying query A': [makeHit(101, 0.95)],
  'qualifying query B': [makeHit(202, 0.9)],
  'below-floor query': [makeHit(303, 0.1)],
};

type ToolCallScript =
  | { kind: 'none' }
  | { kind: 'calls'; queries: string[] }
  | { kind: 'calls-then-throw'; queries: string[] }
  | { kind: 'calls-then-max-turns'; queries: string[] };

let script: ToolCallScript = { kind: 'none' };

type RegisteredKnowledgeSearchTool = {
  handler: (args: { query: string }) => Promise<unknown>;
};

function mockQuery(params: { options: { mcpServers: Record<string, unknown> } }) {
  return (async function* () {
    const server = params.options.mcpServers.community as {
      instance: { _registeredTools: Record<string, RegisteredKnowledgeSearchTool> };
    };
    const knowledgeSearch = server.instance._registeredTools['knowledge_search'];

    if (
      script.kind === 'calls' ||
      script.kind === 'calls-then-throw' ||
      script.kind === 'calls-then-max-turns'
    ) {
      for (const q of script.queries) {
        await knowledgeSearch.handler({ query: q });
      }
    }
    if (script.kind === 'calls-then-throw') {
      throw new Error('simulated upstream failure mid-turn');
    }
    if (script.kind === 'calls-then-max-turns') {
      yield {
        type: 'result',
        subtype: 'error_max_turns',
        result: '',
        session_id: 'sess-1',
        total_cost_usd: 0,
      };
      return;
    }
    yield {
      type: 'result',
      subtype: 'success',
      result: 'here is your answer',
      session_id: 'sess-1',
      total_cost_usd: 0,
    };
  })();
}

// Both query() and searchKnowledge() are static imports inside
// src/agent/core.ts / src/agent/tools.ts, so once those modules have been
// dynamically imported anywhere in this process the bindings are fixed — a
// later t.mock.module call can't retarget them (see
// tests/agentCoreMaxTurns.test.ts for the same trap). Install both mocks
// once and reuse the cached import; `script` is mutated per-test to vary the
// simulated knowledge_search call pattern.
let corePromise: Promise<typeof import('../src/agent/core.js')> | null = null;
async function core(t: { mock: { module: (specifier: string, opts: unknown) => void } }) {
  if (!corePromise) {
    const realSdk = await import('@anthropic-ai/claude-agent-sdk');
    t.mock.module('@anthropic-ai/claude-agent-sdk', { namedExports: { ...realSdk, query: mockQuery } });
    const realRepo = await import('../src/storage/repository.js');
    t.mock.module('../src/storage/repository.js', {
      namedExports: {
        ...realRepo,
        searchKnowledge: async (query: string) => HIT_FIXTURES[query] ?? [],
      },
    });
    corePromise = import('../src/agent/core.js');
  }
  return corePromise;
}

function makeAdapter(): { adapter: PlatformAdapter } {
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage() {},
    async sendMessage(_out: OutgoingMessage) {},
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
  };
  return { adapter };
}

function makeCaller(): CallerContext {
  return {
    platform: 'discord',
    userId: 'member-1',
    userName: 'Member',
    role: 'member',
    conversationId: 'convo-1',
    isDirect: false,
  };
}

test('runAgentTurn: AgentReply.knowledgeEntryId is set to the top-scoring qualifying knowledge_search hit id from the turn (issue #411, acceptance criterion 1)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls', queries: ['qualifying query A'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.knowledgeEntryId, 101);
  assert.equal(reply.ok, true);
});

test('runAgentTurn: AgentReply.knowledgeEntryId is absent when the turn makes no knowledge_search call (issue #411, acceptance criterion 2)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'none' };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.knowledgeEntryId, undefined);
});

test('runAgentTurn: AgentReply.knowledgeEntryId is absent when the only knowledge_search hit falls below the relevance floor (issue #411, acceptance criterion 2)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls', queries: ['below-floor query'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.knowledgeEntryId, undefined);
});

test('runAgentTurn: a later knowledge_search call whose hits miss the floor does not clear an earlier qualifying id — last QUALIFYING call wins, not last call (issue #411, acceptance criterion 3)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls', queries: ['qualifying query A', 'below-floor query'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.knowledgeEntryId, 101, 'the below-floor second call must not clobber the first id');
});

test('runAgentTurn: when two calls both qualify, the LAST qualifying call wins (issue #411, acceptance criterion 3)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls', queries: ['qualifying query A', 'qualifying query B'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.knowledgeEntryId, 202);
});

test('SECURITY: runAgentTurn: AgentReply.knowledgeEntryId is absent when the turn ends in a thrown failure, even though a qualifying knowledge_search call happened first — never a stale id on a failed turn (issue #411, acceptance criterion 5)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls-then-throw', queries: ['qualifying query A'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.ok, false, 'the simulated thrown failure must surface as a failed turn');
  assert.equal(
    reply.knowledgeEntryId,
    undefined,
    'a failed turn must never carry a knowledgeEntryId, even if a qualifying hit occurred before the failure',
  );
});

test('SECURITY: runAgentTurn: AgentReply.knowledgeEntryId is absent on an error_max_turns result, even though a qualifying knowledge_search call happened first — never a stale id on a non-success result (issue #411, acceptance criterion 5)', async (t) => {
  const { runAgentTurn } = await core(t);
  script = { kind: 'calls-then-max-turns', queries: ['qualifying query A'] };

  const reply = await runAgentTurn(makeCaller(), 'hello', makeAdapter().adapter);

  assert.equal(reply.ok, false);
  assert.equal(reply.maxTurnsExceeded, true);
  assert.equal(
    reply.knowledgeEntryId,
    undefined,
    'a max-turns failure must never carry a knowledgeEntryId, even if a qualifying hit occurred before it',
  );
});
