import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { searchKnowledge } from '../src/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// autoAnswerUsageRouter.test.ts. That file pins issue #552's `meta.autoAnswer`
// tag on the `respond()` path only; this file is the ONLY place
// AUTO_ANSWER_CHANNEL_IDS is combined with ALL THREE of
// KNOWLEDGE_SHORTCUT_ENABLED / REPEAT_QUESTION_SHORTCUT_ENABLED /
// REPEAT_MAX_TURNS_SHORTCUT_ENABLED, pinning the automated-review-requested
// fix: the knowledge/repeat/repeat-max-turns shortcut sends
// (sendKnowledgeShortcut/sendRepeatShortcut/sendRepeatMaxTurnsShortcut) also
// stamp meta.autoAnswer when they resolve an auto-answer thread reply, not
// just the full-turn respond() path. Without this, usage_stats undercounted
// real auto-answer thread traffic (any auto-answer reply resolved via a
// shortcut was threaded but never tagged).
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
const hasDb = Boolean(process.env.DATABASE_URL);
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.ACCESS_MODE_DISCORD = 'open';

const RUN = `autoanswer-shortcut-usage-router-${Date.now()}`;
const AUTO_CHAN = `${RUN}-chan`;
process.env.AUTO_ANSWER_CHANNEL_IDS = AUTO_CHAN;
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.REPEAT_QUESTION_SHORTCUT_ENABLED = 'true';
process.env.REPEAT_MAX_TURNS_SHORTCUT_ENABLED = 'true';

const { pool, closeDb } = await import('../src/storage/db.js');
const { Router } = await import('../src/router.js');
const { embed } = await import('../src/storage/embeddings.js');
const { MAX_TURNS_REPLY } = await import('../src/agent/core.js');

await embed('warmup').catch(() => {});

after(async () => {
  if (hasDb) {
    await pool.query(`DELETE FROM interactions WHERE conversation_id LIKE $1`, [`${RUN}%`]);
  }
  await closeDb();
});

type SearchKnowledgeFn = typeof searchKnowledge;

/** Never matches — keeps the knowledge shortcut a no-op for tests that aren't exercising it. */
const NO_HIT_SEARCH: SearchKnowledgeFn = async () => [];

/** Always returns one fixed, high-similarity, human-authored hit, mirroring knowledgeShortcutRouter.test.ts's fixture. */
const FIXED_HIT_SEARCH: SearchKnowledgeFn = async () => [
  {
    id: 1,
    title: 'Rules',
    content: 'Be kind and follow the code of conduct.',
    similarity: 0.95,
    updatedAt: new Date(),
    autoGenerated: false,
    sourceUrl: null,
    sourceTitle: null,
    verifiedAt: null,
    lastRetrievedAt: null,
    sourceUnreachable: null,
    sourceCheckedAt: null,
  },
];

function makeAdapter(): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  threadCalls: { conversationId: string; messageId: string; threadId: string }[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const threadCalls: { conversationId: string; messageId: string; threadId: string }[] = [];
  let threadCounter = 0;
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    async startAutoAnswerThread(conversationId, messageId) {
      threadCounter += 1;
      const threadId = `${RUN}-thread-${threadCounter}`;
      threadCalls.push({ conversationId, messageId, threadId });
      return threadId;
    },
  };
  return {
    adapter,
    sent,
    threadCalls,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: AUTO_CHAN,
    userId: `${RUN}-member-1`,
    userName: 'Ambient User',
    isDirect: false,
    addressedToBot: false,
    timestamp: Date.now(),
    text: `${RUN} default text`,
    messageId: 'default-msg',
    ...overrides,
  };
}

async function outboundMeta(conversationId: string): Promise<Record<string, unknown>> {
  const { rows } = await pool.query(
    `SELECT meta FROM interactions WHERE direction = 'outbound' AND conversation_id = $1
      ORDER BY created_at DESC LIMIT 1`,
    [conversationId],
  );
  assert.equal(rows.length, 1, `expected exactly one outbound interaction recorded for ${conversationId}`);
  return rows[0].meta;
}

test(
  'router: a knowledge shortcut hit resolved via an auto-answer thread records meta.autoAnswer === true (issue #552 review follow-up)',
  { skip: !hasDb },
  async () => {
    const router = new Router(
      async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      20,
      undefined,
      FIXED_HIT_SEARCH,
      async () => {},
    );
    const { adapter, sent, threadCalls, trigger } = makeAdapter();
    router.register(adapter);

    await trigger(
      makeMessage({
        userId: `${RUN}-knowledge-1`,
        messageId: 'knowledge-1',
        text: `${RUN} what are the server rules?`,
      }),
    );

    assert.equal(sent.length, 1);
    assert.equal(
      threadCalls.length,
      1,
      'a knowledge shortcut reply is still threaded like a full auto-answer turn',
    );
    const meta = await outboundMeta(threadCalls[0].threadId);
    assert.equal(meta.autoAnswer, true);
    assert.equal(meta.knowledgeShortcut, true);
  },
);

test(
  'router: a repeat-question shortcut hit resolved via an auto-answer thread records meta.autoAnswer === true (issue #552 review follow-up)',
  { skip: !hasDb },
  async () => {
    let calls = 0;
    const router = new Router(
      async () => {
        calls += 1;
        return { text: 'the context window is 200k tokens', ok: true };
      },
      20,
      undefined,
      NO_HIT_SEARCH,
    );
    const { adapter, sent, threadCalls, trigger } = makeAdapter();
    router.register(adapter);

    const userId = `${RUN}-repeat-1`;
    const text = `${RUN} what is the context window size?`;
    await trigger(makeMessage({ userId, messageId: 'repeat-1a', text }));
    assert.equal(calls, 1);
    assert.equal(threadCalls.length, 1);

    await trigger(makeMessage({ userId, messageId: 'repeat-1b', text }));
    assert.equal(calls, 1, 'the repeat must not spawn a second agent turn');
    assert.equal(sent.length, 2);
    assert.equal(threadCalls.length, 2, 'the replayed answer is still threaded on its own origin post');

    const meta = await outboundMeta(threadCalls[1].threadId);
    assert.equal(meta.autoAnswer, true);
    assert.equal(meta.repeatShortcut, true);
  },
);

test(
  'router: a repeat-max-turns shortcut hit resolved via an auto-answer thread records meta.autoAnswer === true (issue #552 review follow-up)',
  { skip: !hasDb },
  async () => {
    const router = new Router(
      async () => ({ text: MAX_TURNS_REPLY, ok: false, maxTurnsExceeded: true }),
      20,
      undefined,
      NO_HIT_SEARCH,
    );
    const { adapter, sent, threadCalls, trigger } = makeAdapter();
    router.register(adapter);

    const userId = `${RUN}-maxturns-1`;
    const text = `${RUN} a very long ask that always exhausts the turn budget`;
    await trigger(makeMessage({ userId, messageId: 'maxturns-1a', text }));
    assert.equal(threadCalls.length, 1);

    await trigger(makeMessage({ userId, messageId: 'maxturns-1b', text }));
    assert.equal(sent.length, 2);
    assert.equal(
      threadCalls.length,
      2,
      'the replayed max-turns reply is still threaded on its own origin post',
    );

    const meta = await outboundMeta(threadCalls[1].threadId);
    assert.equal(meta.autoAnswer, true);
    assert.equal(meta.repeatMaxTurnsShortcut, true);
  },
);
