import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { searchKnowledge } from '../src/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// knowledgeShortcutRouter.test.ts. This file is the ONLY place
// GUEST_KNOWLEDGE_SHORTCUT_ENABLED is set to 'true' with fully-injected
// fakes (DATABASE_URL stays an unreachable dummy, matching
// knowledgeShortcutRouter.test.ts) — router.test.ts leaves it unset so the
// default-off path stays covered untouched, and
// tests/guestKnowledgeShortcut.test.ts covers the DB-integration,
// security-critical storage invariant end-to-end.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@localhost:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.GUEST_KNOWLEDGE_SHORTCUT_ENABLED = 'true';

const { config } = await import('../src/config.js');
const { Router } = await import('../src/router.js');
const { embed } = await import('../src/storage/embeddings.js');

await embed('warmup').catch(() => {});

type SearchKnowledgeFn = typeof searchKnowledge;

function makeAdapter(overrides: Partial<PlatformAdapter> = {}): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    ...overrides,
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    // Not in SUPER_ADMIN_DISCORD_IDS and unresolvable in `community_users`
    // (DB unreachable in this file) — resolves to 'guest', matching
    // knowledgeShortcutRouter.test.ts's gated-guest test convention.
    userId: 'unknown-guest-1',
    userName: 'A Guest',
    text: 'is this bot free to use?',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 7,
      title: 'Pricing FAQ',
      content: 'Yes — this bot is free for members.',
      similarity,
      updatedAt: new Date(),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      ...overrides,
    },
  ];
}

test('config: GUEST_KNOWLEDGE_SHORTCUT_ENABLED=true is reflected in config.behaviour.guestKnowledgeShortcutEnabled', () => {
  assert.equal(config.behaviour.guestKnowledgeShortcutEnabled, true);
});

test('router (guest knowledge shortcut): a near-exact global match (>= threshold) replies with KB content + admin nudge, never runTurn or the static notice', async () => {
  const recorded: number[][] = [];
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async (ids) => {
      recorded.push(ids);
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Yes — this bot is free for members\./);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
  assert.doesNotMatch(sent[0].text, /member-only/i, 'the static gated notice must not also be sent');
  assert.deepEqual(recorded, [[7]], 'retrieval_count/last_retrieved_at must be bumped for the served entry');
});

test('router (guest knowledge shortcut): a trusted hit with a source_url renders the deterministic citation line (issue #214)', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95, {
      sourceUrl: 'https://docs.anthropic.com/en/api/pricing',
      sourceTitle: 'docs: api/pricing',
      verifiedAt: new Date(),
    }),
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /source: docs: api\/pricing \(https:\/\/docs\.anthropic\.com\/en\/api\/pricing\)/,
  );
  assert.match(sent[0].text, /last verified/);
});

test("SECURITY: router (guest knowledge shortcut): the lookup is scope-restricted to global-only, never the caller's own conversation/platform scope (issue #165)", async () => {
  let seenOpts: unknown;
  const scopeSpy: SearchKnowledgeFn = async (query, caller, topK, opts) => {
    seenOpts = opts;
    return [];
  };
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    scopeSpy,
    async () => {},
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.deepEqual(
    seenOpts,
    { scopeRestriction: 'global-only' },
    'the guest-path lookup must always pass scopeRestriction: global-only',
  );
});

test('router (guest knowledge shortcut): a middling match below threshold falls through to the static gated notice', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.5), // above knowledge_search's 0.35 floor, below the 0.9 shortcut floor
    async () => {
      throw new Error('retrieval must not be recorded for a sub-threshold match');
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

test('router (guest knowledge shortcut): no knowledge hits falls through to the static gated notice', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    async () => [],
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

test('router (guest knowledge shortcut): a lookup failure falls through to the static gated notice rather than dropping the message', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    async () => {
      throw new Error('DB unreachable');
    },
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

// --- Standing 'mi' language preference on the guest knowledge shortcut (issue #435) ---

test("router (guest knowledge shortcut): a gated guest with a standing (possibly stale, ex-member) 'mi' preference gets both KNOWLEDGE_SHORTCUT_SUFFIX_MI and GUEST_KNOWLEDGE_SHORTCUT_NUDGE_MI, from a single lookup", async () => {
  let langCalls = 0;
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => {
      langCalls += 1;
      return 'mi';
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'Yes — this bot is free for members.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.\n\nTonoa tētahi kaiwhakahaere hapori ki te tāpiri i a koe hei mema kia taea ai te kōrero tonu.',
  );
  assert.equal(langCalls, 1, 'both mi strings must share a single getLangPref read, not two');
});

test("router (guest knowledge shortcut): a guest with 'auto' (the default) still gets today's English suffix + nudge, byte-identical", async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => 'auto',
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
});

test('SECURITY: a getLanguagePreference failure on the guest knowledge shortcut still sends the English default, never throws or drops the reply', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => {
      throw new Error('language_prefs read boom');
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await assert.doesNotReject(trigger(makeMessage()));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
});

test('SECURITY: KNOWLEDGE_SHORTCUT_SUFFIX_MI and GUEST_KNOWLEDGE_SHORTCUT_NUDGE_MI are fixed, non-interpolated strings — byte-identical regardless of the served KB entry or caller', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a gated guest');
    },
    20,
    undefined,
    fixedHitSearch(0.95, { content: 'A completely different pricing answer.' }),
    async () => {},
    undefined,
    async () => 'mi',
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ userId: 'another-guest' }));

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'A completely different pricing answer.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.\n\nTonoa tētahi kaiwhakahaere hapori ki te tāpiri i a koe hei mema kia taea ai te kōrero tonu.',
  );
});

test('router (guest knowledge shortcut): a member (non-guest) is completely unaffected by the guest-only flag', async () => {
  const router = new Router(
    async () => ({ text: 'real answer' }),
    20,
    undefined,
    fixedHitSearch(0.99), // would be an instant hit on the guest path — must never be consulted here
    async () => {
      throw new Error(
        'retrieval must not be recorded — KNOWLEDGE_SHORTCUT_ENABLED (the member-tier flag) is unset in this file',
      );
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // 'super-1' is a super admin (SUPER_ADMIN_DISCORD_IDS), so this never
  // reaches the gated-guest branch at all.
  await trigger(makeMessage({ userId: 'super-1' }));

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer', 'the member-tier turn must run untouched by the guest-only flag');
});
