import { test } from 'node:test';
import assert from 'node:assert/strict';
// Community notice-pack registration — the composition-root contract:
// src/index.ts registers the pack in production, so a test whose import
// graph evaluates a notice consumer registers it explicitly here, first.
import '../src/module/strings/notices.js';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/base/platforms/types.js';
import type { hasKnowledgeConflictForId, searchKnowledge } from '../src/base/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// knowledgeShortcutRouter.test.ts. This file is the ONLY place
// GUEST_KNOWLEDGE_SHORTCUT_ENABLED is set to 'true' with fully-injected
// fakes (DATABASE_URL stays an unreachable dummy, matching
// knowledgeShortcutRouter.test.ts) — router.test.ts leaves it unset so the
// default-off path stays covered untouched, and
// tests/guestKnowledgeShortcut.test.ts covers the DB-integration,
// security-critical storage invariant end-to-end.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.GUEST_KNOWLEDGE_SHORTCUT_ENABLED = 'true';

const { config } = await import('../src/base/config.js');
const { Router } = await import('../src/base/router.js');
const { makeRouterDeps } = await import('../src/module/routerWiring.js');
const { KNOWLEDGE_CONFLICT_CAVEAT_TEXT, KNOWLEDGE_STALE_NOTE_MI } =
  await import('../src/module/agent/tools.js');
const { embed } = await import('../src/base/storage/embeddings.js');

await embed('warmup').catch(() => {});

type SearchKnowledgeFn = typeof searchKnowledge;
type CheckConflictFn = typeof hasKnowledgeConflictForId;

function makeAdapter(overrides: Partial<PlatformAdapter> = {}): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    ...overrides,
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    // Not in SUPER_ADMIN_DISCORD_IDS and unresolvable in `community_users`
    // (DB unreachable in this file) — resolves to 'guest', matching
    // knowledgeShortcutRouter.test.ts's gated-guest test convention.
    userId: 'unknown-guest-1',
    userName: 'A Guest',
    text: 'is this bot free to use?',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 7,
      title: 'Pricing FAQ',
      content: 'Yes — this bot is free for members.',
      similarity,
      updatedAt: new Date(),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      sourceUnreachable: null,
      sourceCheckedAt: null,
      ...overrides,
    },
  ];
}

test('config: GUEST_KNOWLEDGE_SHORTCUT_ENABLED=true is reflected in config.behaviour.guestKnowledgeShortcutEnabled', () => {
  assert.equal(config.behaviour.guestKnowledgeShortcutEnabled, true);
});

test('router (guest knowledge shortcut): a near-exact global match (>= threshold) replies with KB content + admin nudge, never runTurn or the static notice', async () => {
  const recorded: number[][] = [];
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async (ids) => {
        recorded.push(ids);
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Yes — this bot is free for members\./);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
  assert.doesNotMatch(sent[0].text, /member-only/i, 'the static gated notice must not also be sent');
  assert.deepEqual(recorded, [[7]], 'retrieval_count/last_retrieved_at must be bumped for the served entry');
});

test('router (guest knowledge shortcut): a hit never records a shortcut_hits row — the "knowledge" kind counts the member-facing shortcut only (issue #440)', async () => {
  const calls: string[] = [];
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      recordShortcutHit: async (kind) => {
        calls.push(kind);
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.deepEqual(calls, [], 'the guest knowledge shortcut must never call recordShortcutHit');
});

test('router (guest knowledge shortcut): a trusted hit with a source_url renders the deterministic citation line (issue #214)', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, {
        sourceUrl: 'https://docs.anthropic.com/en/api/pricing',
        sourceTitle: 'docs: api/pricing',
        verifiedAt: new Date(),
      }),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /source: docs: api\/pricing \(https:\/\/docs\.anthropic\.com\/en\/api\/pricing\)/,
  );
  assert.match(sent[0].text, /last verified/);
});

test('router (guest knowledge shortcut): a hit flagged source_unreachable=true renders the "⚠️ link appears dead" caveat instead of "last verified" (issue #465)', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, {
        sourceUrl: 'https://docs.anthropic.com/en/api/pricing',
        sourceTitle: 'docs: api/pricing',
        verifiedAt: new Date(),
        sourceUnreachable: true,
        sourceCheckedAt: new Date(),
      }),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /⚠️ link appears dead/);
  assert.doesNotMatch(sent[0].text, /last verified/);
});

test("SECURITY: router (guest knowledge shortcut): the lookup is scope-restricted to global-only, never the caller's own conversation/platform scope (issue #165)", async () => {
  let seenOpts: unknown;
  const scopeSpy: SearchKnowledgeFn = async (query, caller, topK, opts) => {
    seenOpts = opts;
    return [];
  };
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: scopeSpy,
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.deepEqual(
    seenOpts,
    { scopeRestriction: 'global-only' },
    'the guest-path lookup must always pass scopeRestriction: global-only',
  );
});

test('router (guest knowledge shortcut): a middling match below threshold falls through to the static gated notice', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.5),
      // above knowledge_search's 0.35 floor, below the 0.9 shortcut floor
      recordShortcutRetrieval: async () => {
        throw new Error('retrieval must not be recorded for a sub-threshold match');
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

test('router (guest knowledge shortcut): no knowledge hits falls through to the static gated notice', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: async () => [],
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

test('router (guest knowledge shortcut): a lookup failure falls through to the static gated notice rather than dropping the message', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: async () => {
        throw new Error('DB unreachable');
      },
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

// --- Standing 'mi' language preference on the guest knowledge shortcut (issue #435) ---

test("router (guest knowledge shortcut): a gated guest with a standing (possibly stale, ex-member) 'mi' preference gets both KNOWLEDGE_SHORTCUT_SUFFIX_MI and GUEST_KNOWLEDGE_SHORTCUT_NUDGE_MI, from a single lookup", async () => {
  let langCalls = 0;
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => {
        langCalls += 1;
        return 'mi';
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'Yes — this bot is free for members.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.\n\nTonoa tētahi kaiwhakahaere hapori ki te tāpiri i a koe hei mema kia taea ai te kōrero tonu.',
  );
  assert.equal(langCalls, 1, 'both mi strings must share a single getLangPref read, not two');
});

test("router (guest knowledge shortcut): a guest with 'auto' (the default) still gets today's English suffix + nudge, byte-identical", async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => 'auto',
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
});

test('SECURITY: a getLanguagePreference failure on the guest knowledge shortcut still sends the English default, never throws or drops the reply', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => {
        throw new Error('language_prefs read boom');
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await assert.doesNotReject(trigger(makeMessage()));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.match(sent[0].text, /ask a community admin/i);
});

test('SECURITY: KNOWLEDGE_SHORTCUT_SUFFIX_MI and GUEST_KNOWLEDGE_SHORTCUT_NUDGE_MI are fixed, non-interpolated strings — byte-identical regardless of the served KB entry or caller', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a gated guest');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, { content: 'A completely different pricing answer.' }),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => 'mi',
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ userId: 'another-guest' }));

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'A completely different pricing answer.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.\n\nTonoa tētahi kaiwhakahaere hapori ki te tāpiri i a koe hei mema kia taea ai te kōrero tonu.',
  );
});

// --- Standing 'mi' language preference on the guest shortcut's staleness tag (issue #848) ---
//
// #435 covered this path's suffix/nudge; #789 covered the member path's
// low-rated caveat. Neither reached the "(may be outdated)" freshness tag on
// THIS (guest) path, which additionally resolved `note` before `lang` — so
// the tag was unconditionally English regardless of a stored 'mi'
// preference. These pin the fix: the reorder (still one getLangPref read)
// plus the lang branch inside formatKnowledgeCitationNote.

test("router (guest knowledge shortcut): a gated guest with a standing 'mi' preference gets KNOWLEDGE_STALE_NOTE_MI on a stale entry, never the English 'may be outdated' tag", async () => {
  const original = config.adminDigest.knowledgeStaleDays;
  config.adminDigest.knowledgeStaleDays = 30;
  try {
    const router = new Router(
      makeRouterDeps({
        runTurn: async () => {
          throw new Error('runTurn must not be called for a gated guest');
        },
        typingRefireMs: 20,
        searchKnowledgeForShortcut: fixedHitSearch(0.95, {
          updatedAt: new Date(Date.now() - 400 * 86_400_000),
        }),
        recordShortcutRetrieval: async () => {},
        getLangPref: async () => 'mi',
      }),
    );
    const { adapter, sent, trigger } = makeAdapter();
    router.register(adapter);

    await trigger(makeMessage());

    assert.equal(sent.length, 1);
    assert.match(sent[0].text, new RegExp(KNOWLEDGE_STALE_NOTE_MI.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    assert.doesNotMatch(sent[0].text, /may be outdated/);
  } finally {
    config.adminDigest.knowledgeStaleDays = original;
  }
});

test("router (guest knowledge shortcut): a stale entry with caller preference 'auto' (no standing preference) keeps the English 'may be outdated' tag, byte-identical to pre-#848 behaviour", async () => {
  const original = config.adminDigest.knowledgeStaleDays;
  config.adminDigest.knowledgeStaleDays = 30;
  try {
    const router = new Router(
      makeRouterDeps({
        runTurn: async () => {
          throw new Error('runTurn must not be called for a gated guest');
        },
        typingRefireMs: 20,
        searchKnowledgeForShortcut: fixedHitSearch(0.95, {
          updatedAt: new Date(Date.now() - 400 * 86_400_000),
        }),
        recordShortcutRetrieval: async () => {},
        getLangPref: async () => 'auto',
      }),
    );
    const { adapter, sent, trigger } = makeAdapter();
    router.register(adapter);

    await trigger(makeMessage());

    assert.equal(sent.length, 1);
    assert.match(sent[0].text, /may be outdated/);
    assert.doesNotMatch(
      sent[0].text,
      new RegExp(KNOWLEDGE_STALE_NOTE_MI.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
    );
  } finally {
    config.adminDigest.knowledgeStaleDays = original;
  }
});

test('router (guest knowledge shortcut): getLangPref is called exactly once per send even with a stale entry — the note/lang reorder must not introduce a second DB read', async () => {
  const original = config.adminDigest.knowledgeStaleDays;
  config.adminDigest.knowledgeStaleDays = 30;
  try {
    let langCalls = 0;
    const router = new Router(
      makeRouterDeps({
        runTurn: async () => {
          throw new Error('runTurn must not be called for a gated guest');
        },
        typingRefireMs: 20,
        searchKnowledgeForShortcut: fixedHitSearch(0.95, {
          updatedAt: new Date(Date.now() - 400 * 86_400_000),
        }),
        recordShortcutRetrieval: async () => {},
        getLangPref: async () => {
          langCalls += 1;
          return 'mi';
        },
      }),
    );
    const { adapter, sent, trigger } = makeAdapter();
    router.register(adapter);

    await trigger(makeMessage());

    assert.equal(sent.length, 1);
    assert.equal(langCalls, 1, 'the note/lang reorder must not duplicate the getLangPref read');
  } finally {
    config.adminDigest.knowledgeStaleDays = original;
  }
});

test('SECURITY: router (guest knowledge shortcut): a getLangPref rejection with a stale entry still renders a complete English reply — content, tag and suffix all present, never dropped or thrown', async () => {
  const original = config.adminDigest.knowledgeStaleDays;
  config.adminDigest.knowledgeStaleDays = 30;
  try {
    const router = new Router(
      makeRouterDeps({
        runTurn: async () => {
          throw new Error('runTurn must not be called for a gated guest');
        },
        typingRefireMs: 20,
        searchKnowledgeForShortcut: fixedHitSearch(0.95, {
          updatedAt: new Date(Date.now() - 400 * 86_400_000),
        }),
        recordShortcutRetrieval: async () => {},
        getLangPref: async () => {
          throw new Error('language_prefs read boom');
        },
      }),
    );
    const { adapter, sent, trigger } = makeAdapter();
    router.register(adapter);

    await assert.doesNotReject(trigger(makeMessage()));

    assert.equal(sent.length, 1);
    assert.match(sent[0].text, /Yes — this bot is free for members\./);
    assert.match(sent[0].text, /may be outdated/);
    assert.match(sent[0].text, /From our knowledge base/i);
  } finally {
    config.adminDigest.knowledgeStaleDays = original;
  }
});

test('router (guest knowledge shortcut): a member (non-guest) is completely unaffected by the guest-only flag', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => ({ text: 'real answer' }),
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.99),
      // would be an instant hit on the guest path — must never be consulted here
      recordShortcutRetrieval: async () => {
        throw new Error(
          'retrieval must not be recorded — KNOWLEDGE_SHORTCUT_ENABLED (the member-tier flag) is unset in this file',
        );
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // 'super-1' is a super admin (SUPER_ADMIN_DISCORD_IDS), so this never
  // reaches the gated-guest branch at all.
  await trigger(makeMessage({ userId: 'super-1' }));

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer', 'the member-tier turn must run untouched by the guest-only flag');
});

// --- V1 scope boundary: the conflict caveat (issue #918) stays member-only ---
//
// Mirrors #337's own deliberate exclusion of the low-rated caveat from this
// path ("the gated-guest shortcut still never passes it") — a gated guest
// isn't yet a member, and this proposal changes nothing about that existing
// posture. `sendGuestKnowledgeShortcut` has no `checkKnowledgeConflict` call
// site at all, so this pins the boundary rather than exercising a branch.

test('SECURITY: router (guest knowledge shortcut): sendGuestKnowledgeShortcut never consults checkKnowledgeConflict — reply is byte-identical whether it would resolve true or false (issue #918)', async () => {
  const buildRouter = (checkKnowledgeConflict: CheckConflictFn) =>
    new Router(
      makeRouterDeps({
        runTurn: async () => {
          throw new Error('runTurn must not be called for a gated guest');
        },
        typingRefireMs: 20,
        // checkPaused
        searchKnowledgeForShortcut: fixedHitSearch(0.95),
        recordShortcutRetrieval: async () => {},
        // searchMemberInterestsForSelfFn
        checkKnowledgeConflict: checkKnowledgeConflict,
      }),
    );

  let calledWithTrue = false;
  const { adapter: adapterTrue, sent: sentTrue, trigger: triggerTrue } = makeAdapter();
  buildRouter(async () => {
    calledWithTrue = true;
    return true;
  }).register(adapterTrue);
  await triggerTrue(makeMessage());

  let calledWithFalse = false;
  const { adapter: adapterFalse, sent: sentFalse, trigger: triggerFalse } = makeAdapter();
  buildRouter(async () => {
    calledWithFalse = true;
    return false;
  }).register(adapterFalse);
  await triggerFalse(makeMessage());

  assert.equal(sentTrue.length, 1);
  assert.equal(sentFalse.length, 1);
  assert.equal(
    sentTrue[0].text,
    sentFalse[0].text,
    'the guest reply must be byte-identical regardless of what checkKnowledgeConflict would resolve to',
  );
  assert.doesNotMatch(
    sentTrue[0].text,
    new RegExp(KNOWLEDGE_CONFLICT_CAVEAT_TEXT.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
  );
  assert.equal(calledWithTrue, false, 'the guest shortcut path must never consult checkKnowledgeConflict');
  assert.equal(calledWithFalse, false, 'the guest shortcut path must never consult checkKnowledgeConflict');
});
