import { test } from 'node:test';
import assert from 'node:assert/strict';
// Community notice-pack registration — the composition-root contract:
// src/index.ts registers the pack in production, so a test whose import
// graph evaluates a notice consumer registers it explicitly here, first.
import './support/registerNotices.js';
import type {
  IncomingMessage,
  OutgoingMessage,
  PlatformAdapter,
} from '@swampratnz/agent-base/platforms/types.js';
import type {
  hasKnowledgeConflictForId,
  searchKnowledge,
} from '@swampratnz/agent-base/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// ackShortcutRouter.test.ts. This file is the ONLY place
// KNOWLEDGE_SHORTCUT_ENABLED is set to 'true' — router.test.ts and
// ackShortcutRouter.test.ts leave it unset so the default-off path stays
// covered untouched, and the node test runner isolates env per test file.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';

const { config } = await import('@swampratnz/agent-base/config.js');
const { Router } = await import('@swampratnz/agent-base/router.js');
const { makeRouterDeps } = await import('../src/module/routerWiring.js');
await import('./support/registerToolRegistry.js');
const { KNOWLEDGE_CONFLICT_CAVEAT_TEXT } = await import('../src/module/agent/tools.js');
const { embed } = await import('@swampratnz/agent-base/storage/embeddings.js');

await embed('warmup').catch(() => {});

type SearchKnowledgeFn = typeof searchKnowledge;
type CheckConflictFn = typeof hasKnowledgeConflictForId;

function makeAdapter(overrides: Partial<PlatformAdapter> = {}): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    ...overrides,
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    userId: 'super-1',
    userName: 'Test User',
    text: 'what are the server rules?',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 1,
      title: 'Rules',
      content: 'Be kind and follow the code of conduct.',
      similarity,
      updatedAt: new Date(),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      sourceUnreachable: null,
      sourceCheckedAt: null,
      ...overrides,
    },
  ];
}

test('config: KNOWLEDGE_SHORTCUT_ENABLED=true is reflected in config.behaviour.knowledgeShortcutEnabled', () => {
  assert.equal(config.behaviour.knowledgeShortcutEnabled, true);
});

test('config: KNOWLEDGE_SHORTCUT_THRESHOLD defaults to a strict 0.9', () => {
  assert.equal(config.behaviour.knowledgeShortcutThreshold, 0.9);
});

test('router (knowledge shortcut): a near-exact match (>= threshold) skips runTurn and returns the KB content', async () => {
  const recorded: number[][] = [];
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async (ids) => {
        recorded.push(ids);
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.deepEqual(recorded, [[1]], 'retrieval_count/last_retrieved_at must be bumped for the served entry');
});

test('router (knowledge shortcut): a hit records a shortcut_hits row of kind "knowledge" (issue #440)', async () => {
  const calls: string[] = [];
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      recordShortcutHit: async (kind) => {
        calls.push(kind);
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.deepEqual(calls, ['knowledge']);
});

test('SECURITY: router (knowledge shortcut): an auto-researched near-exact match is NOT direct-served — it falls through to a full turn (where knowledge_search quarantines it)', async () => {
  let ranTurn = false;
  const autoHitSearch: SearchKnowledgeFn = async () => [
    {
      id: 7,
      title: 'Claude Code — recent updates (auto-researched)',
      content: 'unreviewed web-derived briefing',
      similarity: 0.98, // well above the shortcut threshold
      updatedAt: new Date(),
      autoGenerated: true,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      sourceUnreachable: null,
      sourceCheckedAt: null,
    },
  ];
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        ranTurn = true;
        return { text: 'real answer' };
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: autoHitSearch,
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.ok(ranTurn, 'an auto-researched hit must fall through to a full agent turn, never be direct-served');
  assert.doesNotMatch(
    sent[0]?.text ?? '',
    /From our knowledge base/i,
    'the trust-maximising shortcut must not fire for unreviewed auto content',
  );
});

test('router (knowledge shortcut): a middling match below threshold falls through to a normal agent turn', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => ({ text: 'real answer' }),
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.5),
      // above knowledge_search's 0.35 floor, below the 0.9 shortcut floor
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer', 'must get the real agent reply, not a shortcut reply');
});

test('router (knowledge shortcut): no knowledge hits falls through to a normal agent turn', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => ({ text: 'real answer' }),
      typingRefireMs: 20,
      searchKnowledgeForShortcut: async () => [],
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer');
});

test('router (knowledge shortcut): a lookup failure falls through to a normal agent turn rather than dropping the message', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => ({ text: 'real answer' }),
      typingRefireMs: 20,
      searchKnowledgeForShortcut: async () => {
        throw new Error('DB unreachable');
      },
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer');
});

// The flag-disabled path (including "flag off falls through regardless of
// similarity") is covered in router.test.ts, which leaves
// KNOWLEDGE_SHORTCUT_ENABLED unset — this file is the ONLY place it's set to
// 'true', mirroring ackShortcutRouter.test.ts's convention.

test('router (knowledge shortcut): a trusted hit with a source_url renders the deterministic citation line (issue #214)', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, {
        sourceUrl: 'https://docs.anthropic.com/en/api/messages',
        sourceTitle: 'docs: api/messages',
        verifiedAt: new Date(),
      }),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /source: docs: api\/messages \(https:\/\/docs\.anthropic\.com\/en\/api\/messages\)/,
  );
  assert.match(sent[0].text, /last verified/);
});

test('router (knowledge shortcut): a hit flagged source_unreachable=true renders the "⚠️ link appears dead" caveat instead of "last verified" (issue #465)', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, {
        sourceUrl: 'https://docs.anthropic.com/en/api/messages',
        sourceTitle: 'docs: api/messages',
        verifiedAt: new Date(),
        sourceUnreachable: true,
        sourceCheckedAt: new Date(),
      }),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /⚠️ link appears dead/);
  assert.doesNotMatch(sent[0].text, /last verified/);
});

test('router (knowledge shortcut): a hit with no source_url renders no citation line', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.doesNotMatch(sent[0].text, /source:/i);
});

test('router (knowledge shortcut): the freshness note is a no-op when KNOWLEDGE_STALE_DAYS is unset (default 0)', async () => {
  assert.equal(config.adminDigest.knowledgeStaleDays, 0, 'this test file leaves KNOWLEDGE_STALE_DAYS unset');
  const ancient = new Date(Date.now() - 365 * 86_400_000);
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, { updatedAt: ancient }),
      recordShortcutRetrieval: async () => {},
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.doesNotMatch(sent[0].text, /may be outdated/);
});

test('router (knowledge shortcut): the shortcut path still respects the gated-guest gate ahead of it', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.99),
      recordShortcutRetrieval: async () => {
        throw new Error('retrieval must not be recorded for a gated-out guest');
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // Default ACCESS_MODE_DISCORD is 'gated'; this user is not a super admin
  // and unresolvable in community_users (DB unreachable in this test), so it
  // resolves to 'guest' and must hit the gated-guest branch, never the
  // knowledge shortcut.
  await trigger(makeMessage({ userId: 'unknown-guest-1' }));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

// --- Standing 'mi' language preference on the knowledge shortcut (issue #435) ---

test("router (knowledge shortcut): a caller with a standing 'mi' language preference gets the reply suffixed with KNOWLEDGE_SHORTCUT_SUFFIX_MI", async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => 'mi',
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'Be kind and follow the code of conduct.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.',
  );
  assert.match(
    sent[0].text,
    /Be kind and follow the code of conduct\./,
    'the KB hit.content must stay unchanged',
  );
});

test("router (knowledge shortcut): a caller with 'auto' (the default) still gets today's English suffix, byte-identical", async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => 'auto',
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
  );
});

test('SECURITY: a getLanguagePreference failure on the knowledge shortcut still sends the English default, never throws or drops the reply', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => {
        throw new Error('language_prefs read boom');
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await assert.doesNotReject(trigger(makeMessage()));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
});

test('SECURITY: KNOWLEDGE_SHORTCUT_SUFFIX_MI is a fixed, non-interpolated string — byte-identical regardless of the served KB entry or caller', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95, {
        content: 'A completely different knowledge entry.',
      }),
      recordShortcutRetrieval: async () => {},
      getLangPref: async () => 'mi',
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ userId: 'super-1' }));

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai\.$/,
    'the suffix must be the fixed literal appended after the (varying) KB content',
  );
});

// KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is left unset in this file (see
// lowRatedCaveatRouter.test.ts, the ONLY file that sets it) — so it must
// stay at its default-disabled 0, and a hit that would clear a lower
// threshold must produce byte-identical output to today's shortcut reply
// (issue #337 acceptance criteria 3 + 4).
test('config: KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is disabled (default 0) in this file', () => {
  assert.equal(config.behaviour.knowledgeLowRatedCaveatMinUnhelpful, 0);
});

test('router (knowledge shortcut): with the low-rated caveat left at its default-disabled setting, the extra lookup is never issued and the reply is byte-identical to the pre-#337 shortcut reply', async () => {
  const router = new Router(
    makeRouterDeps({
      runTurn: async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      },
      typingRefireMs: 20,
      searchKnowledgeForShortcut: fixedHitSearch(0.95),
      recordShortcutRetrieval: async () => {},
      checkLowRatedKnowledge: async () => {
        throw new Error(
          'the low-rated lookup must never fire when KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is 0',
        );
      },
    }),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
  );
  assert.doesNotMatch(sent[0].text, /rate_answer/);
});

// --- Unreconciled-conflict caveat on the member shortcut (issue #918) ---
//
// `hasConflictAmongIds` (issue #389) can't answer this: it short-circuits to
// `false` for any array shorter than 2 elements, and the shortcut only ever
// serves one hit. `hasKnowledgeConflictForId` is the single-id sibling this
// path needed. Unlike the low-rated caveat above, this lookup is
// unconditional (no config gate) — matching knowledge_search/`/kb`'s own
// unconditional conflict check — so every test in this file that leaves
// `checkKnowledgeConflict` at its real default resolves it against the
// unreachable dummy DATABASE_URL and fails safe to `false`.

/** Builds a full Router so `checkKnowledgeConflict` (a late positional ctor param) can be injected/spied without listing every field in between. */
function makeRouterForConflictCaveat(opts: {
  runTurn?: ConstructorParameters<typeof Router>[0];
  searchKnowledgeForShortcut: SearchKnowledgeFn;
  recordShortcutRetrieval?: ConstructorParameters<typeof Router>[4];
  checkKnowledgeConflict: CheckConflictFn;
}): InstanceType<typeof Router> {
  return new Router(
    makeRouterDeps({
      runTurn:
        opts.runTurn ??
        (async () => {
          throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
        }),
      typingRefireMs: 20,
      // checkPaused
      searchKnowledgeForShortcut: opts.searchKnowledgeForShortcut,
      recordShortcutRetrieval: opts.recordShortcutRetrieval ?? (async () => {}),
      // searchMemberInterestsForSelfFn
      checkKnowledgeConflict: opts.checkKnowledgeConflict,
    }),
  );
}

test('SECURITY: router (knowledge shortcut): a served entry with an unreconciled conflict gets KNOWLEDGE_CONFLICT_CAVEAT_TEXT appended (issue #918)', async () => {
  const calls: number[] = [];
  const router = makeRouterForConflictCaveat({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkKnowledgeConflict: async (id) => {
      calls.push(id);
      return true;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.match(
    sent[0].text,
    new RegExp(`\\(${KNOWLEDGE_CONFLICT_CAVEAT_TEXT.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\)`),
  );
  assert.deepEqual(
    calls,
    [1],
    'SECURITY: the check is keyed on the served hit id, never a full-conversation batch',
  );
});

test('router (knowledge shortcut): a served entry with no conflict omits KNOWLEDGE_CONFLICT_CAVEAT_TEXT, byte-identical to the pre-#918 shortcut reply', async () => {
  let called = false;
  const router = makeRouterForConflictCaveat({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkKnowledgeConflict: async () => {
      called = true;
      return false;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.ok(called, 'the lookup still fires (unconditional) — it just resolves no-conflict');
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
  );
  assert.doesNotMatch(sent[0].text, /disagree with each other/);
});

test('SECURITY: router (knowledge shortcut): a conflict-lookup failure falls back to omitting the caveat rather than blocking or erroring the reply', async () => {
  const router = makeRouterForConflictCaveat({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkKnowledgeConflict: async () => {
      throw new Error('DB unreachable');
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await assert.doesNotReject(trigger(makeMessage()));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.doesNotMatch(sent[0].text, /disagree with each other/);
});
