import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { searchKnowledge } from '../src/storage/repository.js';
import type { StaleKnowledgeAlertCandidate } from '../src/agent/tools.js';

// config.ts validates env at import time — provide a dummy environment before
// importing anything that (transitively) loads it, matching
// knowledgeGapAlert.router.test.ts. This file is the ONLY place
// KNOWLEDGE_STALE_ALERT_ENABLED is set to 'true' — router.test.ts leaves it
// unset (default off) so that byte-identical-by-default path stays covered
// untouched, and the node test runner isolates env per test file.
//
// It also sets KNOWLEDGE_SHORTCUT_ENABLED/GUEST_KNOWLEDGE_SHORTCUT_ENABLED —
// unlike the gap-cluster alert (which only ever fires from the
// knowledge_search tool path), issue #701's stale-knowledge alert fires from
// THREE serve paths (knowledge_search + both knowledge shortcuts), so this
// file combines all three flags to exercise all of them. Every alert-firing
// assertion below injects `claimStaleKnowledgeAlertFn` directly, so it never
// depends on the real DB-backed staleness computation — `tools.test.ts` and
// `repository.test.ts` cover that against a real Postgres instead.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.KNOWLEDGE_STALE_ALERT_ENABLED = 'true';
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.GUEST_KNOWLEDGE_SHORTCUT_ENABLED = 'true';
// Small cap so the rate-cap test below doesn't need to fire dozens of calls.
process.env.KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR = '3';

const { config } = await import('../src/config.js');
const { Router } = await import('../src/router.js');

type SearchKnowledgeFn = typeof searchKnowledge;

function makeAdapter(): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    userId: 'super-1',
    userName: 'Test User',
    text: 'what are the club rules',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 42,
      title: 'Club rules',
      content: 'Be kind and follow the code of conduct.',
      similarity,
      updatedAt: new Date(Date.now() - 400 * 86_400_000),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      sourceUnreachable: null,
      sourceCheckedAt: null,
      ...overrides,
    },
  ];
}

const FIXED_CLAIM: StaleKnowledgeAlertCandidate = {
  id: 42,
  title: 'Club rules',
  content: 'Be kind and follow the code of conduct.',
  updatedAt: new Date(Date.now() - 400 * 86_400_000),
};

/**
 * Builds a Router with a stub `runTurn` (1st arg), a `searchKnowledgeForShortcut`
 * (4th arg), spy `notifyAdminsFn` (14th arg), and a `claimStaleKnowledgeAlertFn`
 * (17th arg) — mirrors knowledgeGapAlert.router.test.ts's
 * `makeRouterWithSpies` shape.
 */
function makeRouterWithSpies(opts: {
  runTurn?: Parameters<typeof Router>[0];
  searchKnowledgeForShortcut?: SearchKnowledgeFn;
  claimStaleKnowledgeAlertFn?: (entry: unknown) => Promise<StaleKnowledgeAlertCandidate | null>;
}) {
  const notifyCalls: { message: string; excludeUserId: string }[] = [];
  const router = new Router(
    opts.runTurn ??
      (async () => {
        throw new Error('runTurn must not be called unless the test expects a full turn');
      }),
    20,
    undefined,
    opts.searchKnowledgeForShortcut ?? (async () => []),
    async () => {},
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    async (
      _adapterFor: (platform: string) => PlatformAdapter | undefined,
      message: string,
      excludeUserId: string,
    ) => {
      notifyCalls.push({ message, excludeUserId });
    },
    undefined,
    undefined,
    opts.claimStaleKnowledgeAlertFn ?? (async () => null),
  );
  return { router, notifyCalls };
}

test('config: KNOWLEDGE_STALE_ALERT_ENABLED reads true and KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR reads the overridden value', () => {
  assert.equal(config.knowledgeStaleAlert.enabled, true);
  assert.equal(config.knowledgeStaleAlert.rateLimitPerHour, 3);
});

test('router (stale-knowledge alert, knowledge_search path): reply.staleKnowledgeAlerts fires exactly one notifyAdmins call naming the title and a relative age (issue #701 acceptance criterion 1)', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    runTurn: async () => ({
      text: 'Here is what I found.',
      ok: true,
      staleKnowledgeAlerts: [FIXED_CLAIM],
    }),
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-search' }));

  assert.equal(sent[0].text, 'Here is what I found.', 'the member-facing reply is untouched');
  assert.equal(notifyCalls.length, 1, 'exactly one notifyAdmins call');
  assert.match(notifyCalls[0].message, /Club rules/);
  assert.match(notifyCalls[0].message, /may be outdated/);
  assert.equal(notifyCalls[0].excludeUserId, 'super-1');
});

test('router (stale-knowledge alert, knowledge_search path): no claims this turn (staleKnowledgeAlerts absent) never calls notifyAdmins', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    runTurn: async () => ({ text: 'Sorry, I could not find anything on that.', ok: true }),
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-no-claim' }));

  assert.equal(sent[0].text, 'Sorry, I could not find anything on that.');
  assert.equal(notifyCalls.length, 0);
});

test('router (stale-knowledge alert, knowledge shortcut path): a served near-exact hit that claimStaleKnowledgeAlertFn claims fires exactly one notifyAdmins call (issue #701 acceptance criterion 1)', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    claimStaleKnowledgeAlertFn: async (entry) => {
      const e = entry as { id: number };
      return e.id === 42 ? FIXED_CLAIM : null;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-shortcut' }));

  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.equal(notifyCalls.length, 1, 'exactly one notifyAdmins call');
  assert.match(notifyCalls[0].message, /Club rules/);
});

test('router (stale-knowledge alert, knowledge shortcut path): claimStaleKnowledgeAlertFn returning null never calls notifyAdmins', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    claimStaleKnowledgeAlertFn: async () => null,
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-shortcut-no-claim' }));

  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.equal(notifyCalls.length, 0);
});

test('router (stale-knowledge alert, guest knowledge shortcut path): a served near-exact hit for a gated guest that claimStaleKnowledgeAlertFn claims fires exactly one notifyAdmins call (issue #701 acceptance criterion 1)', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    claimStaleKnowledgeAlertFn: async (entry) => {
      const e = entry as { id: number };
      return e.id === 42 ? FIXED_CLAIM : null;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // Not in SUPER_ADMIN_DISCORD_IDS and unresolvable in `community_users`
  // (DB unreachable) — resolves to 'guest' in the default gated access mode,
  // matching guestKnowledgeShortcutRouter.test.ts's convention.
  await trigger(makeMessage({ userId: 'unknown-guest-1', conversationId: 'chan-guest-shortcut' }));

  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.equal(notifyCalls.length, 1, 'exactly one notifyAdmins call');
  assert.match(notifyCalls[0].message, /Club rules/);
  assert.equal(notifyCalls[0].excludeUserId, 'unknown-guest-1');
});

test('SECURITY: router (stale-knowledge alert): the alert DM body contains only the entry title and a relative age — never the conversation id, query text, or caller identity (issue #701 acceptance criterion 5a)', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    runTurn: async () => ({
      text: 'reply',
      ok: true,
      staleKnowledgeAlerts: [FIXED_CLAIM],
    }),
  });
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(
    makeMessage({
      conversationId: 'secret-channel-id-should-not-leak',
      text: 'secret query text that must not leak',
      userId: 'super-1',
    }),
  );

  assert.equal(notifyCalls.length, 1);
  const message = notifyCalls[0].message;
  assert.doesNotMatch(message, /secret-channel-id-should-not-leak/, 'the conversation id must never appear');
  assert.doesNotMatch(message, /secret query text/i, 'the member query text must never appear');
  assert.match(message, /Club rules/, 'the entry title must appear');
  assert.match(message, /may be outdated/, 'a relative-age freshness note must appear');
});

test('SECURITY: router (stale-knowledge alert): an untitled entry falls back to a truncateForEcho-bounded content excerpt, never the raw unbounded content (issue #701 acceptance criterion 5a)', async () => {
  const longContent = 'x'.repeat(500);
  const { router, notifyCalls } = makeRouterWithSpies({
    runTurn: async () => ({
      text: 'reply',
      ok: true,
      staleKnowledgeAlerts: [
        { id: 99, title: null, content: longContent, updatedAt: new Date(Date.now() - 400 * 86_400_000) },
      ],
    }),
  });
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-untitled' }));

  assert.equal(notifyCalls.length, 1);
  const message = notifyCalls[0].message;
  assert.ok(
    message.length < longContent.length,
    'an over-long excerpt must be truncated, never echoed in full',
  );
  assert.match(message, /x+\.\.\./, 'truncated text ends with the standard truncateForEcho ellipsis');
});

test('SECURITY: router (stale-knowledge alert): once KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR is exhausted within the hour, further claimed entries queue no further DM (issue #701 acceptance criterion 5c)', async () => {
  const { router, notifyCalls } = makeRouterWithSpies({
    runTurn: async (_caller, prompt: string) => ({
      text: 'reply',
      ok: true,
      staleKnowledgeAlerts: [
        {
          id: Number(prompt.replace(/\D/g, '')),
          title: prompt,
          content: prompt,
          updatedAt: new Date(Date.now() - 400 * 86_400_000),
        },
      ],
    }),
  });
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  const limit = config.knowledgeStaleAlert.rateLimitPerHour;
  for (let i = 0; i < limit; i += 1) {
    await trigger(makeMessage({ text: `capped entry ${i}`, conversationId: `chan-cap-${i}` }));
  }
  assert.equal(notifyCalls.length, limit, 'every claim within the cap must notify');

  // One more claim, past the cap — the DB stamp already happened inside the
  // (mocked) claim itself, so this asserts only the DM-suppression half of
  // acceptance criterion 5c; the "still stamped" half is covered by
  // reserveStaleKnowledgeAlert's own repository.test.ts coverage.
  await trigger(makeMessage({ text: 'over-cap entry 999', conversationId: 'chan-over-cap' }));

  assert.equal(notifyCalls.length, limit, 'the over-cap claim must not notify — the cap is not exceeded');
});

test("SECURITY: router (stale-knowledge alert): fireStaleKnowledgeAlert only ever calls notifyAdminsFn — never notifySuperAdmins, superAdminIds, or any other broader-audience send path — so the alert's recipient set stays exactly listAdmins(), no broader (issue #701 acceptance criterion 5b)", () => {
  const source = readFileSync(new URL('../src/router.ts', import.meta.url), 'utf8');
  const start = source.indexOf('private async fireStaleKnowledgeAlert(');
  assert.notEqual(start, -1, 'fireStaleKnowledgeAlert method not found');
  // The method body ends where the next method (`sweep`) is declared.
  const end = source.indexOf('private sweep(): void {', start);
  assert.notEqual(end, -1, 'sweep (the next method) not found');
  assert.ok(end > start, 'sweep must be declared after fireStaleKnowledgeAlert');
  const body = source.slice(start, end);
  assert.match(body, /this\.notifyAdminsFn\(/, 'fireStaleKnowledgeAlert must call notifyAdminsFn');
  assert.doesNotMatch(
    body,
    /notifySuperAdmins|superAdminIds|sendDirectMessage/,
    'fireStaleKnowledgeAlert must never reach a broader-audience recipient set than notifyAdminsFn (listAdmins()) itself resolves',
  );
});
