import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { searchKnowledge } from '../src/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// ackShortcutRouter.test.ts. This file is the ONLY place
// KNOWLEDGE_SHORTCUT_ENABLED is set to 'true' — router.test.ts and
// ackShortcutRouter.test.ts leave it unset so the default-off path stays
// covered untouched, and the node test runner isolates env per test file.
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@localhost:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';

const { config } = await import('../src/config.js');
const { Router } = await import('../src/router.js');
const { embed } = await import('../src/storage/embeddings.js');

await embed('warmup').catch(() => {});

type SearchKnowledgeFn = typeof searchKnowledge;

function makeAdapter(overrides: Partial<PlatformAdapter> = {}): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    ...overrides,
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    userId: 'super-1',
    userName: 'Test User',
    text: 'what are the server rules?',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 1,
      title: 'Rules',
      content: 'Be kind and follow the code of conduct.',
      similarity,
      updatedAt: new Date(),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      ...overrides,
    },
  ];
}

test('config: KNOWLEDGE_SHORTCUT_ENABLED=true is reflected in config.behaviour.knowledgeShortcutEnabled', () => {
  assert.equal(config.behaviour.knowledgeShortcutEnabled, true);
});

test('config: KNOWLEDGE_SHORTCUT_THRESHOLD defaults to a strict 0.9', () => {
  assert.equal(config.behaviour.knowledgeShortcutThreshold, 0.9);
});

test('router (knowledge shortcut): a near-exact match (>= threshold) skips runTurn and returns the KB content', async () => {
  const recorded: number[][] = [];
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async (ids) => {
      recorded.push(ids);
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.deepEqual(recorded, [[1]], 'retrieval_count/last_retrieved_at must be bumped for the served entry');
});

test('SECURITY: router (knowledge shortcut): an auto-researched near-exact match is NOT direct-served — it falls through to a full turn (where knowledge_search quarantines it)', async () => {
  let ranTurn = false;
  const autoHitSearch: SearchKnowledgeFn = async () => [
    {
      id: 7,
      title: 'Claude Code — recent updates (auto-researched)',
      content: 'unreviewed web-derived briefing',
      similarity: 0.98, // well above the shortcut threshold
      updatedAt: new Date(),
      autoGenerated: true,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
    },
  ];
  const router = new Router(
    async () => {
      ranTurn = true;
      return { text: 'real answer' };
    },
    20,
    undefined,
    autoHitSearch,
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.ok(ranTurn, 'an auto-researched hit must fall through to a full agent turn, never be direct-served');
  assert.doesNotMatch(
    sent[0]?.text ?? '',
    /From our knowledge base/i,
    'the trust-maximising shortcut must not fire for unreviewed auto content',
  );
});

test('router (knowledge shortcut): a middling match below threshold falls through to a normal agent turn', async () => {
  const router = new Router(
    async () => ({ text: 'real answer' }),
    20,
    undefined,
    fixedHitSearch(0.5), // above knowledge_search's 0.35 floor, below the 0.9 shortcut floor
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer', 'must get the real agent reply, not a shortcut reply');
});

test('router (knowledge shortcut): no knowledge hits falls through to a normal agent turn', async () => {
  const router = new Router(
    async () => ({ text: 'real answer' }),
    20,
    undefined,
    async () => [],
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer');
});

test('router (knowledge shortcut): a lookup failure falls through to a normal agent turn rather than dropping the message', async () => {
  const router = new Router(
    async () => ({ text: 'real answer' }),
    20,
    undefined,
    async () => {
      throw new Error('DB unreachable');
    },
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer');
});

// The flag-disabled path (including "flag off falls through regardless of
// similarity") is covered in router.test.ts, which leaves
// KNOWLEDGE_SHORTCUT_ENABLED unset — this file is the ONLY place it's set to
// 'true', mirroring ackShortcutRouter.test.ts's convention.

test('router (knowledge shortcut): a trusted hit with a source_url renders the deterministic citation line (issue #214)', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95, {
      sourceUrl: 'https://docs.anthropic.com/en/api/messages',
      sourceTitle: 'docs: api/messages',
      verifiedAt: new Date(),
    }),
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /source: docs: api\/messages \(https:\/\/docs\.anthropic\.com\/en\/api\/messages\)/,
  );
  assert.match(sent[0].text, /last verified/);
});

test('router (knowledge shortcut): a hit with no source_url renders no citation line', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.doesNotMatch(sent[0].text, /source:/i);
});

test('router (knowledge shortcut): the freshness note is a no-op when KNOWLEDGE_STALE_DAYS is unset (default 0)', async () => {
  assert.equal(config.adminDigest.knowledgeStaleDays, 0, 'this test file leaves KNOWLEDGE_STALE_DAYS unset');
  const ancient = new Date(Date.now() - 365 * 86_400_000);
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95, { updatedAt: ancient }),
    async () => {},
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.doesNotMatch(sent[0].text, /may be outdated/);
});

test('router (knowledge shortcut): the shortcut path still respects the gated-guest gate ahead of it', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called');
    },
    20,
    undefined,
    fixedHitSearch(0.99),
    async () => {
      throw new Error('retrieval must not be recorded for a gated-out guest');
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // Default ACCESS_MODE_DISCORD is 'gated'; this user is not a super admin
  // and unresolvable in community_users (DB unreachable in this test), so it
  // resolves to 'guest' and must hit the gated-guest branch, never the
  // knowledge shortcut.
  await trigger(makeMessage({ userId: 'unknown-guest-1' }));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /member-only/i);
});

// --- Standing 'mi' language preference on the knowledge shortcut (issue #435) ---

test("router (knowledge shortcut): a caller with a standing 'mi' language preference gets the reply suffixed with KNOWLEDGE_SHORTCUT_SUFFIX_MI", async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => 'mi',
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    'Be kind and follow the code of conduct.\n\n— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai.',
  );
  assert.match(
    sent[0].text,
    /Be kind and follow the code of conduct\./,
    'the KB hit.content must stay unchanged',
  );
});

test("router (knowledge shortcut): a caller with 'auto' (the default) still gets today's English suffix, byte-identical", async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => 'auto',
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
  );
});

test('SECURITY: a getLanguagePreference failure on the knowledge shortcut still sends the English default, never throws or drops the reply', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    async () => {
      throw new Error('language_prefs read boom');
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await assert.doesNotReject(trigger(makeMessage()));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
});

test('SECURITY: KNOWLEDGE_SHORTCUT_SUFFIX_MI is a fixed, non-interpolated string — byte-identical regardless of the served KB entry or caller', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95, { content: 'A completely different knowledge entry.' }),
    async () => {},
    undefined,
    async () => 'mi',
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ userId: 'super-1' }));

  assert.equal(sent.length, 1);
  assert.match(
    sent[0].text,
    /— Nō tā mātou pātengi mōhiotanga; pātai mai kia whakamāramatia mehemea kāore tēnei e tino whakautu ana i tāu pātai\.$/,
    'the suffix must be the fixed literal appended after the (varying) KB content',
  );
});

// KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is left unset in this file (see
// lowRatedCaveatRouter.test.ts, the ONLY file that sets it) — so it must
// stay at its default-disabled 0, and a hit that would clear a lower
// threshold must produce byte-identical output to today's shortcut reply
// (issue #337 acceptance criteria 3 + 4).
test('config: KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is disabled (default 0) in this file', () => {
  assert.equal(config.behaviour.knowledgeLowRatedCaveatMinUnhelpful, 0);
});

test('router (knowledge shortcut): with the low-rated caveat left at its default-disabled setting, the extra lookup is never issued and the reply is byte-identical to the pre-#337 shortcut reply', async () => {
  const router = new Router(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    20,
    undefined,
    fixedHitSearch(0.95),
    async () => {},
    undefined,
    undefined,
    async () => {
      throw new Error(
        'the low-rated lookup must never fire when KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is 0',
      );
    },
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
  );
  assert.doesNotMatch(sent[0].text, /rate_answer/);
});
