import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/platforms/types.js';
import type { isKnowledgeLowRated, searchKnowledge } from '../src/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment
// before importing anything that (transitively) loads it, matching
// knowledgeShortcutRouter.test.ts. This file is the ONLY place
// KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL is set to a non-zero value —
// knowledgeShortcutRouter.test.ts and router.test.ts leave it unset so the
// default-off (byte-for-byte unchanged) path stays covered untouched, and
// the node test runner isolates env per test file (issue #337).
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.GUEST_KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL = '2';

const { config } = await import('../src/config.js');
const { Router } = await import('../src/router.js');
const { KNOWLEDGE_LOW_RATED_CAVEAT_TEXT } = await import('../src/agent/tools.js');
const { embed } = await import('../src/storage/embeddings.js');

await embed('warmup').catch(() => {});

type SearchKnowledgeFn = typeof searchKnowledge;
type CheckLowRatedFn = typeof isKnowledgeLowRated;

function makeAdapter(overrides: Partial<PlatformAdapter> = {}): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
    ...overrides,
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    userId: 'super-1',
    userName: 'Test User',
    text: 'what are the server rules?',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge` returning one fixed hit, regardless of query text. */
function fixedHitSearch(
  similarity: number,
  overrides: Partial<Awaited<ReturnType<SearchKnowledgeFn>>[number]> = {},
): SearchKnowledgeFn {
  return async () => [
    {
      id: 42,
      title: 'Rules',
      content: 'Be kind and follow the code of conduct.',
      similarity,
      updatedAt: new Date(),
      autoGenerated: false,
      sourceUrl: null,
      sourceTitle: null,
      verifiedAt: null,
      lastRetrievedAt: null,
      sourceUnreachable: null,
      sourceCheckedAt: null,
      ...overrides,
    },
  ];
}

/** Builds a full 8-arg Router so `checkLowRatedKnowledge` (the 8th ctor param) can be injected/spied. */
function makeRouter(opts: {
  runTurn?: ConstructorParameters<typeof Router>[0];
  searchKnowledgeForShortcut: SearchKnowledgeFn;
  recordShortcutRetrieval?: ConstructorParameters<typeof Router>[4];
  checkLowRatedKnowledge: CheckLowRatedFn;
}): InstanceType<typeof Router> {
  return new Router(
    opts.runTurn ??
      (async () => {
        throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
      }),
    20,
    undefined,
    opts.searchKnowledgeForShortcut,
    opts.recordShortcutRetrieval ?? (async () => {}),
    undefined,
    undefined,
    opts.checkLowRatedKnowledge,
  );
}

test('config: KNOWLEDGE_LOW_RATED_CAVEAT_MIN_UNHELPFUL=2 is reflected in config.behaviour.knowledgeLowRatedCaveatMinUnhelpful', () => {
  assert.equal(config.behaviour.knowledgeLowRatedCaveatMinUnhelpful, 2);
});

test('router (low-rated caveat): a low-rated entry served via the member shortcut gets the fixed caveat appended to the note (issue #337)', async () => {
  const calls: Array<[number, number]> = [];
  const router = makeRouter({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkLowRatedKnowledge: async (entryId, minUnhelpful) => {
      calls.push([entryId, minUnhelpful]);
      return true;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.match(
    sent[0].text,
    new RegExp(KNOWLEDGE_LOW_RATED_CAVEAT_TEXT.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
  );
  assert.deepEqual(
    calls,
    [[42, 2]],
    'SECURITY: the served entry id and the configured threshold cross the render boundary — never a raw count',
  );
});

test('router (low-rated caveat): an entry below threshold produces byte-identical output to the pre-#337 shortcut reply — no caveat', async () => {
  let called = false;
  const router = makeRouter({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkLowRatedKnowledge: async () => {
      called = true;
      return false;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.ok(called, 'the lookup still fires (feature is enabled) — it just resolves below-threshold');
  assert.equal(
    sent[0].text,
    "Be kind and follow the code of conduct.\n\n— From our knowledge base; ask me to explain if this doesn't quite answer it.",
    'must match the exact pre-#337 shortcut reply with no caveat and no citation note',
  );
  assert.doesNotMatch(sent[0].text, /rate_answer/);
});

test('router (low-rated caveat): a lookup failure falls back to omitting the caveat rather than failing the reply', async () => {
  const router = makeRouter({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    checkLowRatedKnowledge: async () => {
      throw new Error('DB unreachable');
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /Be kind and follow the code of conduct\./);
  assert.doesNotMatch(sent[0].text, /rate_answer/);
});

test('router (low-rated caveat): the lookup fires ONLY on the shortcut-eligible top-1 hit path — never on a full agent turn', async () => {
  let called = false;
  const router = makeRouter({
    runTurn: async () => ({ text: 'real answer' }),
    searchKnowledgeForShortcut: fixedHitSearch(0.5), // below the 0.9 shortcut floor -> falls through to a full turn
    checkLowRatedKnowledge: async () => {
      called = true;
      return true;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage());

  assert.equal(sent.length, 1);
  assert.equal(sent[0].text, 'real answer');
  assert.equal(called, false, 'the low-rated lookup must never fire on the full-turn (non-shortcut) path');
});

test('SECURITY: router (low-rated caveat): the gated-guest shortcut is unaffected even with the caveat enabled — no lookup, no caveat text', async () => {
  let called = false;
  const router = makeRouter({
    searchKnowledgeForShortcut: fixedHitSearch(0.95),
    recordShortcutRetrieval: async () => {},
    checkLowRatedKnowledge: async () => {
      called = true;
      return true;
    },
  });
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  // Not a super admin and unresolvable in community_users (DB unreachable in
  // this file) -> resolves to 'guest', matching
  // guestKnowledgeShortcutRouter.test.ts's convention.
  await trigger(makeMessage({ userId: 'unknown-guest-1' }));

  assert.equal(sent.length, 1);
  assert.match(sent[0].text, /From our knowledge base/i);
  assert.doesNotMatch(sent[0].text, /rate_answer/);
  assert.equal(called, false, 'the guest shortcut path must never consult the low-rated lookup');
});
