import { test } from 'node:test';
import assert from 'node:assert/strict';
// Community notice-pack registration — the composition-root contract:
// src/index.ts registers the pack in production, so a test whose import
// graph evaluates a notice consumer registers it explicitly here, first.
import '../src/module/strings/notices.js';
import type { IncomingMessage, OutgoingMessage, PlatformAdapter } from '../src/base/platforms/types.js';
import type { searchKnowledge } from '../src/base/storage/repository.js';

// config.ts validates env at import time — provide a dummy environment before
// importing anything that (transitively) loads it, matching
// knowledgeGapAlert.router.test.ts. This is the ONLY place
// KNOWLEDGE_STALE_ALERT_ENABLED is set to 'true' — router.test.ts and
// knowledgeShortcutRouter.test.ts leave it unset (default off) so that
// byte-identical-by-default path stays covered untouched, and the node test
// runner isolates env per test file (issue #701, same convention as issue
// #650's own router test).
process.env.CLAUDE_CODE_OAUTH_TOKEN ??= 'test-token';
process.env.DISCORD_BOT_TOKEN ??= 'test-token';
process.env.DISCORD_GUILD_ID ??= '1';
process.env.DATABASE_URL ??= 'postgres://test:test@127.0.0.1:5432/test';
process.env.WHATSAPP_PROVIDER ??= 'disabled';
process.env.SUPER_ADMIN_DISCORD_IDS ??= 'super-1';
process.env.KNOWLEDGE_STALE_ALERT_ENABLED = 'true';
// Small cap so the rate-cap test below doesn't need to fire dozens of calls.
process.env.KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR = '3';
process.env.KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.GUEST_KNOWLEDGE_SHORTCUT_ENABLED = 'true';
process.env.KNOWLEDGE_STALE_DAYS = '30';

const { config } = await import('../src/base/config.js');
const { Router } = await import('../src/base/router.js');
const { makeRouterDeps } = await import('../src/module/routerWiring.js');

type SearchKnowledgeFn = typeof searchKnowledge;
type StaleInfo = { title: string | null; content: string; updatedAt: Date } | null;

function makeAdapter(): {
  adapter: PlatformAdapter;
  sent: OutgoingMessage[];
  trigger: (msg: IncomingMessage) => Promise<void>;
} {
  let handler: ((msg: IncomingMessage) => Promise<void> | void) | null = null;
  const sent: OutgoingMessage[] = [];
  const adapter: PlatformAdapter = {
    platform: 'discord',
    adminCapabilities: new Set(),
    async start() {},
    async stop() {},
    isConnected: () => true,
    onMessage(h) {
      handler = h;
    },
    async sendMessage(out) {
      sent.push(out);
    },
    async sendDirectMessage() {},
    async conversationsForUser() {
      return [];
    },
    async performAdminAction() {
      return '';
    },
    async sendTypingIndicator() {},
  };
  return {
    adapter,
    sent,
    trigger: async (msg) => {
      if (!handler) throw new Error('adapter.onMessage was never registered — call router.register() first');
      await handler(msg);
    },
  };
}

function makeMessage(overrides: Partial<IncomingMessage> = {}): IncomingMessage {
  return {
    platform: 'discord',
    conversationId: 'chan-1',
    userId: 'super-1',
    userName: 'Test User',
    text: 'what time does the ferry leave',
    isDirect: false,
    addressedToBot: true,
    timestamp: Date.now(),
    ...overrides,
  };
}

/** A fake `searchKnowledge`/shortcut lookup returning one fixed, stale hit, regardless of query text. */
function fixedStaleHitSearch(similarity: number): SearchKnowledgeFn {
  return async () =>
    [
      {
        id: 501,
        title: 'Stale FAQ entry',
        content: 'This is a stale FAQ answer nobody has edited in a long time.',
        similarity,
        updatedAt: new Date(Date.now() - 400 * 86_400_000),
        autoGenerated: false,
        sourceUrl: null,
        sourceTitle: null,
        verifiedAt: null,
        lastRetrievedAt: null,
        sourceUnreachable: null,
        sourceCheckedAt: null,
      },
    ] as Awaited<ReturnType<SearchKnowledgeFn>>;
}

/**
 * Builds a Router with a stub `runTurn` (1st arg), an optional stub
 * `searchKnowledgeForShortcut` (4th arg), plus spy `notifyAdminsFn` (14th
 * arg) and `markStaleKnowledgeAlertedFn` (17th arg) — the router-level
 * exercise of the stale-knowledge alert (issue #701) never needs a real
 * agent turn, mirroring `knowledgeGapAlert.router.test.ts`'s
 * `makeRouterWithSpies` shape exactly. `markStaleResponses` maps a
 * knowledge id to a queue of responses `markStaleKnowledgeAlertedFn` returns
 * on successive calls for that id (shift per call, `null` once exhausted) —
 * this is how tests simulate the real atomic gate's single-shot/re-arm
 * behaviour (covered for real, against a live DB, in repository.test.ts)
 * without needing one here.
 */
function makeRouterWithSpies(
  runTurn: Parameters<typeof Router>[0],
  markStaleResponses: Map<number, StaleInfo[]>,
  searchKnowledgeForShortcut?: SearchKnowledgeFn,
) {
  const notifyCalls: { message: string; excludeUserId: string }[] = [];
  const markStaleCalls: number[] = [];
  const markStaleFn = async (id: number): Promise<StaleInfo> => {
    markStaleCalls.push(id);
    const queue = markStaleResponses.get(id);
    return queue && queue.length > 0 ? queue.shift()! : null;
  };
  const router = new Router(
    makeRouterDeps({
      runTurn: runTurn,
      typingRefireMs: 20,
      searchKnowledgeForShortcut: searchKnowledgeForShortcut,
      notifyAdminsFn: async (
        _adapterFor: (platform: string) => PlatformAdapter | undefined,
        message: string,
        excludeUserId: string,
      ) => {
        notifyCalls.push({ message, excludeUserId });
      },
      markStaleKnowledgeAlertedFn: markStaleFn,
    }),
  );
  return { router, notifyCalls, markStaleCalls };
}

test('config: KNOWLEDGE_STALE_ALERT_ENABLED reads true and KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR reads the overridden value', () => {
  assert.equal(config.knowledgeStaleAlert.enabled, true);
  assert.equal(config.knowledgeStaleAlert.rateLimitPerHour, 3);
});

test('router (knowledge_search stale alert): a served-stale id fires exactly one notifyAdmins call naming the title and a relative age, and stamps via markStaleKnowledgeAlertedFn (issue #701 acceptance criterion 1)', async () => {
  const info: StaleInfo = {
    title: 'Old parking rules',
    content: 'Park in the north lot only.',
    updatedAt: new Date(Date.now() - 20 * 86_400_000),
  };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => ({ text: 'Here is what I found.', ok: true, turnState: { staleKnowledgeAlertIds: [77] } }),
    new Map([[77, [info]]]),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-stale-1' }));

  assert.equal(sent[0].text, 'Here is what I found.', 'the member-facing reply is untouched');
  assert.deepEqual(markStaleCalls, [77], 'the served id must be passed to markStaleKnowledgeAlertedFn');
  assert.equal(notifyCalls.length, 1, 'exactly one notifyAdmins call');
  assert.match(notifyCalls[0].message, /Old parking rules/);
  assert.match(notifyCalls[0].message, /~20 days ago/);
  assert.equal(notifyCalls[0].excludeUserId, 'super-1');
});

test('router (knowledge_search stale alert): multiple stale ids served in one turn each fire their own notifyAdmins call (issue #701 acceptance criterion 1)', async () => {
  const infoA: StaleInfo = { title: 'Entry A', content: 'content a', updatedAt: new Date() };
  const infoB: StaleInfo = { title: 'Entry B', content: 'content b', updatedAt: new Date() };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => ({ text: 'reply', ok: true, turnState: { staleKnowledgeAlertIds: [1, 2] } }),
    new Map([
      [1, [infoA]],
      [2, [infoB]],
    ]),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-stale-multi' }));

  assert.deepEqual(markStaleCalls.sort(), [1, 2]);
  assert.equal(notifyCalls.length, 2, 'each stale served entry gets its own notifyAdmins call');
});

test('router (knowledge_search stale alert): no staleKnowledgeAlertIds on the reply never calls markStaleKnowledgeAlertedFn or notifyAdmins (issue #701 acceptance criterion 4)', async () => {
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => ({ text: 'Sorry, I could not find anything on that.', ok: true }),
    new Map(),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-no-stale' }));

  assert.equal(sent[0].text, 'Sorry, I could not find anything on that.');
  assert.equal(markStaleCalls.length, 0);
  assert.equal(notifyCalls.length, 0);
});

test('router (knowledge_search stale alert): single-shot per episode — a second serve of the same, already-alerted id (markStaleKnowledgeAlertedFn returns null) fires no further notifyAdmins call (issue #701 acceptance criterion 2)', async () => {
  const info: StaleInfo = { title: 'Repeatedly served entry', content: 'content', updatedAt: new Date() };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => ({ text: 'reply', ok: true, turnState: { staleKnowledgeAlertIds: [99] } }),
    new Map([[99, [info, null]]]),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-single-shot-1' }));
  await trigger(makeMessage({ conversationId: 'chan-single-shot-2' }));

  assert.deepEqual(markStaleCalls, [99, 99], 'both serves must still consult the gate');
  assert.equal(notifyCalls.length, 1, 'only the first serve — the one that passed the gate — notifies');
});

test('router (knowledge_search stale alert): re-arm on edit — once markStaleKnowledgeAlertedFn passes the gate again (simulating an admin edit bumping updated_at), a fresh serve notifies a second time (issue #701 acceptance criterion 3)', async () => {
  const infoBeforeEdit: StaleInfo = { title: 'Re-armed entry', content: 'content', updatedAt: new Date() };
  const infoAfterEdit: StaleInfo = { title: 'Re-armed entry', content: 'new content', updatedAt: new Date() };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => ({ text: 'reply', ok: true, turnState: { staleKnowledgeAlertIds: [55] } }),
    new Map([[55, [infoBeforeEdit, null, infoAfterEdit]]]),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-rearm-1' }));
  await trigger(makeMessage({ conversationId: 'chan-rearm-2' }));
  await trigger(makeMessage({ conversationId: 'chan-rearm-3' }));

  assert.deepEqual(markStaleCalls, [55, 55, 55]);
  assert.equal(
    notifyCalls.length,
    2,
    'the gate passing again (post-edit) must notify a second time, independent of the earlier single-shot',
  );
});

test('SECURITY: router (stale-knowledge alert): the alert DM body is a strict subset of what list_knowledge already returns — title (or excerpt) + relative age only, never a member/user identity, query text, or conversation id (issue #701 acceptance criterion 5a)', async () => {
  const longContent = 'x'.repeat(500);
  const info: StaleInfo = { title: null, content: longContent, updatedAt: new Date() };
  const { router, notifyCalls } = makeRouterWithSpies(
    async () => ({ text: 'reply', ok: true, turnState: { staleKnowledgeAlertIds: [12] } }),
    new Map([[12, [info]]]),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(
    makeMessage({
      conversationId: 'secret-channel-id-should-not-leak',
      userName: 'Secret Member Name',
      text: 'my raw member query text',
    }),
  );

  assert.equal(notifyCalls.length, 1);
  const message = notifyCalls[0].message;
  assert.doesNotMatch(message, /secret-channel-id-should-not-leak/, 'the conversation id must never appear');
  assert.doesNotMatch(message, /Secret Member Name/, 'the serving member identity must never appear');
  assert.doesNotMatch(message, /my raw member query text/, 'the member query text must never appear');
  assert.ok(
    message.length < longContent.length,
    "an untitled entry's over-long content must be truncated (truncateForEcho), never echoed in full",
  );
  assert.match(message, /x+\.\.\./, 'truncated text ends with the standard truncateForEcho ellipsis');
});

test('SECURITY: router (stale-knowledge alert): the alert is delivered only via notifyAdminsFn (the listAdmins()-scoped path) — no member-facing sendMessage carries the alert body (issue #701 acceptance criterion 5b)', async () => {
  const info: StaleInfo = { title: 'Admin-only alert content', content: 'content', updatedAt: new Date() };
  const { router, notifyCalls } = makeRouterWithSpies(
    async () => ({ text: 'member reply text', ok: true, turnState: { staleKnowledgeAlertIds: [21] } }),
    new Map([[21, [info]]]),
  );
  const { adapter, sent, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-recipient-scope' }));

  assert.equal(notifyCalls.length, 1);
  assert.equal(sent.length, 1);
  assert.doesNotMatch(
    sent[0].text,
    /Admin-only alert content/,
    'the member-facing sendMessage reply must never carry the alert body',
  );
});

test('SECURITY: router (stale-knowledge alert): once KNOWLEDGE_STALE_ALERT_RATE_LIMIT_PER_HOUR is exhausted within the hour, further alerts are suppressed (no notifyAdmins call) but the entry is still stamped via markStaleKnowledgeAlertedFn so it does not retry-storm (issue #701 acceptance criterion 5c)', async () => {
  const makeInfo = (n: number): StaleInfo => ({
    title: `Entry ${n}`,
    content: 'content',
    updatedAt: new Date(),
  });
  const responses = new Map<number, StaleInfo[]>();
  const limit = 3; // config.knowledgeStaleAlert.rateLimitPerHour, per the env override above
  for (let i = 0; i < limit + 1; i += 1) {
    responses.set(i, [makeInfo(i)]);
  }
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async (_caller, prompt: string) => ({
      text: 'reply',
      ok: true,
      turnState: { staleKnowledgeAlertIds: [Number(prompt.replace(/\D/g, ''))] },
    }),
    responses,
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  assert.equal(config.knowledgeStaleAlert.rateLimitPerHour, limit);
  for (let i = 0; i < limit; i += 1) {
    await trigger(makeMessage({ text: `capped entry ${i}`, conversationId: `chan-cap-${i}` }));
  }
  assert.equal(notifyCalls.length, limit, 'every serve within the cap must notify');

  // One more, past the cap.
  await trigger(makeMessage({ text: `capped entry ${limit}`, conversationId: 'chan-over-cap' }));

  assert.equal(notifyCalls.length, limit, 'the over-cap serve must not notify — the cap is not exceeded');
  assert.equal(
    markStaleCalls.length,
    limit + 1,
    'the over-cap serve must still be stamped via markStaleKnowledgeAlertedFn — unlike the knowledge-gap ' +
      'alert precedent, a rate-limited stale entry is never left unstamped, so it cannot retry-storm on ' +
      'every subsequent serve',
  );
});

// --- Shortcut call sites (sendKnowledgeShortcut / sendGuestKnowledgeShortcut) ---

test('router (knowledge shortcut, member): a near-exact match on a stale entry fires the stale-knowledge alert exactly like the knowledge_search path (issue #701 acceptance criterion 1)', async () => {
  const info: StaleInfo = { title: 'Stale FAQ entry', content: 'content', updatedAt: new Date() };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => {
      throw new Error('runTurn must not be called for a near-exact knowledge-shortcut match');
    },
    new Map([[501, [info]]]),
    fixedStaleHitSearch(0.95),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  await trigger(makeMessage({ conversationId: 'chan-shortcut-member' }));

  assert.deepEqual(markStaleCalls, [501]);
  assert.equal(notifyCalls.length, 1);
});

test('router (knowledge shortcut, gated guest): a near-exact match on a stale entry also fires the stale-knowledge alert — the served entry is admin-authored data, not guest data (issue #701 acceptance criterion 1)', async () => {
  const info: StaleInfo = { title: 'Stale FAQ entry', content: 'content', updatedAt: new Date() };
  const { router, notifyCalls, markStaleCalls } = makeRouterWithSpies(
    async () => {
      throw new Error('runTurn must not be called for a gated-guest near-exact match');
    },
    new Map([[501, [info]]]),
    fixedStaleHitSearch(0.95),
  );
  const { adapter, trigger } = makeAdapter();
  router.register(adapter);

  // Default ACCESS_MODE_DISCORD is 'gated'; this user is not a super admin
  // and unresolvable in community_users, so it resolves to 'guest' and hits
  // sendGuestKnowledgeShortcut, matching knowledgeShortcutRouter.test.ts's
  // own gated-guest derivation.
  await trigger(makeMessage({ userId: 'unknown-guest-stale-1', conversationId: 'chan-shortcut-guest' }));

  assert.deepEqual(markStaleCalls, [501]);
  assert.equal(notifyCalls.length, 1);
});
