import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { config } from '../config.js';
import { logger } from '../logger.js';
import { closeDb } from '../storage/db.js';
import { listContextDigests, type ContextDigest } from '../storage/repository.js';

/**
 * Anonymised community-context export (issue #53): renders `context_digests`
 * into docs/COMMUNITY-CONTEXT.md so the research loop can ground proposals in
 * what the community actually needs. This file is the hard privacy boundary
 * between the DB and anything that reaches the (private) GitHub repo, so the
 * controls are enforced HERE in code, not by prompt:
 *
 *  - Aggregate only: topic labels, counts, summaries, period stamps. No raw
 *    message content, no user ids, no display names, no conversation ids —
 *    and no interaction ids either (refs stay internal to the DB).
 *  - k-anonymity floor (CONTEXT_EXPORT_MIN_DISTINCT_USERS, >=2, default 3 —
 *    small enough to keep signal in a modest community, large enough that no
 *    single person's activity is an identifiable line): topics carried by
 *    fewer distinct authors are dropped, and the drop is logged, not hidden.
 *  - A PII scrub over the model-written summaries (emails, phone numbers,
 *    @handles, URL query strings) as belt-and-braces.
 *
 * Residual (documented in SECURITY.md): the scrub is lexical, not semantic —
 * a summary can still be semantically identifying. Acceptable only because
 * the sink is a PRIVATE repo; re-evaluate before ever making it public.
 *
 * Committing the regenerated file is a HUMAN step (the bot never pushes);
 * see docs/PIPELINE.md.
 */

const EXPORT_HEADER = '# Community context (anonymised export)';

/**
 * Lexical PII scrub for model-written summary text. Order matters: emails
 * before handles (so the @domain half is already gone), URLs before phones
 * (so digits inside stripped query strings don't linger).
 */
export function scrubPII(text: string): string {
  return (
    text
      // email addresses
      .replace(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g, '[email]')
      // URLs: keep origin+path, drop query/fragment (where user tokens live)
      .replace(/(https?:\/\/[^\s?#]+)[?#]\S*/g, '$1')
      // ...and redact long token-shaped PATH segments too (reset links etc.
      // often carry the token in the path, not the query)
      .replace(/(https?:\/\/[^\s]*?\/)[A-Za-z0-9_-]{20,}/g, '$1[token]')
      // @handles
      .replace(/@[A-Za-z0-9_.-]{2,}/g, '[handle]')
      // phone-number-shaped runs (8+ digits, optional +/separators)
      .replace(/\+?\d(?:[\s().-]?\d){7,}/g, '[phone]')
  );
}

export interface ExportOptions {
  generatedAt: Date;
  windowDays: number;
  minDistinctUsers: number;
}

export interface ExportResult {
  markdown: string;
  included: number;
  droppedBelowFloor: number;
}

/**
 * Pure renderer, unit-tested directly. Consumes digests, applies the export
 * k-floor and the scrub, and emits only aggregate fields — a digest's
 * exampleRefs (internal interaction ids) are deliberately never rendered.
 */
export function renderCommunityContextExport(
  digests: readonly ContextDigest[],
  opts: ExportOptions,
): ExportResult {
  const eligible = digests.filter((d) => d.distinctUsers >= opts.minDistinctUsers);
  const droppedBelowFloor = digests.length - eligible.length;

  const lines: string[] = [
    EXPORT_HEADER,
    '',
    '<!-- AUTO-GENERATED by src/context/export.ts (issue #53). Do not hand-edit. -->',
    '<!-- Aggregate-only, k-floored, scrubbed. See docs/SECURITY.md ("Community-context export"). -->',
    '',
    `- Generated: ${opts.generatedAt.toISOString()}`,
    `- Window: last ${opts.windowDays} day(s) of context digests`,
    `- Anonymity floor: topics need >= ${opts.minDistinctUsers} distinct authors to appear`,
    '',
  ];

  if (eligible.length === 0) {
    lines.push(
      '_No topics cleared the export floor in this window. (Either the context builder has not run, or activity was too concentrated to export safely.)_',
    );
  } else {
    lines.push('## Recurring community topics', '');
    for (const d of eligible) {
      const period = `${d.periodStart.toISOString().slice(0, 10)}..${d.periodEnd.toISOString().slice(0, 10)}`;
      lines.push(
        `### ${scrubPII(d.topic)}`,
        `- ${d.questionCount} message(s) from ${d.distinctUsers} distinct people · ${period}`,
        `- ${scrubPII(d.summary)}`,
        '',
      );
    }
  }

  return { markdown: `${lines.join('\n').trimEnd()}\n`, included: eligible.length, droppedBelowFloor };
}

/** Fetch, render, and write the export file. Called after builder runs (and via `npm run export:context`). */
export async function writeCommunityContextExport(
  path = config.contextExport.path,
): Promise<{ included: number; droppedBelowFloor: number }> {
  const digests = await listContextDigests(config.contextExport.windowDays, 100);
  const { markdown, included, droppedBelowFloor } = renderCommunityContextExport(digests, {
    generatedAt: new Date(),
    windowDays: config.contextExport.windowDays,
    minDistinctUsers: config.contextExport.minDistinctUsers,
  });
  await writeFile(path, markdown, 'utf8');
  if (droppedBelowFloor > 0) {
    logger.info({ droppedBelowFloor }, 'Community-context export dropped topics below the k-floor');
  }
  logger.info({ path, included }, 'Community-context export written');
  return { included, droppedBelowFloor };
}

// Allow running directly: `npm run export:context` (against DATABASE_URL).
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  writeCommunityContextExport()
    .then(() => closeDb())
    .then(() => process.exit(0))
    .catch((err) => {
      logger.error({ err }, 'Community-context export failed');
      process.exit(1);
    });
}
